### ISSUE TITLE
if you edit a tag on the projects page and press on tags you get an stack error

### ISSUE THREAD

**Issue by raymond-blok** [remcodezwart/project_beheer#8]
A PHP Error was encountered

Severity: Notice

Message: Undefined offset: 0

Filename: models/Projects_model.php

Line Number: 51

Backtrace:

File: C:\wamp64\www\project_beheer\application\models\Projects_model.php
Line: 51
Function: _error_handler

File: C:\wamp64\www\project_beheer\application\controllers\Projects.php
Line: 132
Function: getProject

File: C:\wamp64\www\project_beheer\public\index.php
Line: 315
Function: require_once

**Comment by Damianves** [comment]
This is for all the pages
